### PR TITLE
add spectre cf and w3 flags

### PR DESCRIPTION
**Pull request by sbatten**

### CODE REVIEW

**Review by TylerLeonhardt — APPROVED** [review]
Though I'd prefer if you pulled it out the condition since it doesn't have to be in there.

**Comment by deepak1556** [comment]
Merging this can wait till next when we move to Electron 16 and Node 16 which would allow us to drop 14.x which requires build agent changes similar to https://github.com/microsoft/node-native-keymap/pull/39#issuecomment-1057038073

**Comment by sbatten** [comment]
@deepak1556 can we merge and just wait to publish a new version?

**Comment by sbatten** [comment]
will leave this one in the condition since we have it anyway

**Comment by deepak1556** [comment]
@sbatten I have adjusted the CI on `main`, can you rebase again and this should be good to go.

**Comment by TylerLeonhardt** [comment]
Good opportunity to check this in the repo settings so you can click to rebase
image

**Pull request merged**
